openapi: 3.0.1
info:
  title: monster-dretch
  x-cortex-tag: monster-dretch
  x-cortex-custom-metadata:
    alignment: neutral-evil
    type: plant
    challenge_rating: 16
    legendary: false
    armor_class: 22
    hit_points: 243
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-dretch
      alias: github-token-test
